# Временная конфигурация для получения SSL сертификата

server {
    listen 80;
    server_name api.anmicius.ru;

    location /.well-known/acme-challenge/ {
        root /var/www;
    }

    location / {
        return 301 https://$server_name$request_uri;
    }
}

server {
    listen 80;
    server_name anmicius.ru www.anmicius.ru admin.anmicius.ru minio.anmicius.ru;

    location /.well-known/acme-challenge/ {
        root /var/www;
    }

    location / {
        return 301 https://$server_name$request_uri;
    }
}
